# Servidor
#server.port=8080
# Servidor

# Base de datos PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/codelingo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
codelingo.jwt.secret=${JWT_SECRET:Y29kZWxpbmdvLXNlY3JldC1rZXktcGFyYS1kZXNhcnJvbGxvLWxvY2FsLTIwMjQ=}
codelingo.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Email (SendGrid)
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${MAIL_PASSWORD:reemplazar}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
sendgrid.api.key=${SENDGRID_API_KEY:reemplazar-en-produccion}
# URL del frontend
codelingo.frontend.url=${FRONTEND_URL:https://codelingo-tau.vercel.app}

# Nombre de la app
spring.application.name=backend-codelingo

logging.level.org.springframework.security=INFO
logging.level.com.codelingo=INFO

server.address=0.0.0.0
server.port=${PORT:8080}